# Generated by Django 4.2.10 on 2024-06-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=0, max_length=20)),
                ('New_price', models.CharField(max_length=5)),
                ('Old_price', models.CharField(max_length=5)),
                ('Photo', models.ImageField(upload_to='product/')),
                ('Dec', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('PH', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('userno', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('Gender', models.CharField(max_length=6)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=10)),
                ('course', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(default=0, max_length=254)),
            ],
        ),
    ]
