# Generated by Django 4.2.10 on 2024-06-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(max_length=16)),
                ('Expiry', models.CharField(max_length=5)),
                ('Cvv', models.CharField(max_length=5)),
                ('Card_Name', models.CharField(max_length=25)),
            ],
        ),
    ]
