# Generated by Django 5.0.6 on 2024-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=25)),
                ('home_price', models.CharField(max_length=25)),
                ('home_image', models.ImageField(upload_to='product/')),
                ('h6_head', models.CharField(max_length=25)),
                ('down_heading', models.CharField(max_length=30)),
            ],
        ),
    ]
