# Generated by Django 5.0.6 on 2024-06-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_home_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_add',
            name='home_image',
            field=models.ImageField(upload_to='home_product/'),
        ),
    ]
