# Generated by Django 5.0.3 on 2024-07-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_otp_verification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp_verification',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000026857F44C20>', max_length=200),
        ),
    ]
