# Generated by Django 5.0.3 on 2024-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_delete_otp_verification_user_otp_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001F123BF7B00>', max_length=200),
        ),
    ]
