# Generated by Django 5.0.3 on 2024-07-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1000)),
                ('userfn', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002043B387B00>', max_length=200),
        ),
    ]
