# Generated by Django 5.0.3 on 2024-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_theme_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Name',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='home_add',
            name='down_heading',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='home_add',
            name='h6_head',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='home_add',
            name='home_price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='home_add',
            name='main_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000026D91467B00>', max_length=200),
        ),
    ]
