# Generated by Django 5.0.3 on 2024-07-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
