# Generated by Django 5.0 on 2024-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_profile1_delete_theme_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Category',
            field=models.CharField(default='000', max_length=20),
        ),
    ]
