# Generated by Django 5.0 on 2024-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_student_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('userno', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('Gender', models.CharField(max_length=6)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=10)),
                ('course', models.CharField(default=0, max_length=30)),
                ('Category', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Faculty', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Category',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Student', max_length=20),
        ),
    ]
