# Generated by Django 5.0 on 2024-07-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_faculty_alter_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Field',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
