# Generated by Django 5.0 on 2024-07-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=400),
        ),
    ]
