# Generated by Django 5.0 on 2024-07-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Register_Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('UserName', models.CharField(max_length=40)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Password_id', models.CharField(max_length=30)),
                ('Country_Code', models.CharField(max_length=7)),
                ('Phone_number_id', models.CharField(max_length=12)),
            ],
        ),
    ]
