"""
Django settings for mysite1 project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
# import paypalrestsdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ep*f@=&j7c97#)x_bqa2(uqsk4u-!$9=i@n7_qwm*e(6$17$f3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'education',
    'captcha',
    'social_django',
    'education2',
    'Admin',
    'mysite1',
    # 'paypal.standard.ipn'
] 

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.github.GithubOAuth2',
]

# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'mysite1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates', 'templates/App1', 'templates/App2', 'templates/App3', 'templates/App4'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'python89',
        'HOST': 'AM-ITC-PC-85\\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'DRIVER': 'ODBC Driver 17 for SQL Server'
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

...

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],

}

...

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'education/static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
# LOGIN_URL = '/accounts/Login/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = 'dilipkarmakar1978@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = 'qnba qeqy sfvn goef'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USER_SSL = False
fail_silently = False

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '445412783848-d6rfevlufb66t55vus3bb8dkm2so2ppf.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = 'http://127.0.0.1:8000/social-auth/complete/google-oauth2/'

LOGIN_URL = ''
LOGIN_REDIRECT_URL = '/'

SOCIAL_AUTH_FACEBOOK_KEY = '774014468270340'
SOCIAL_AUTH_FACEBOOK_SECRET = '912f4bff011a682c7c6db402da7d2dff'
SOCIAL_AUTH_FACEBOOK_REDIRECT_URI = 'http://127.0.0.1:8000/social-auth/complete/facebook-oauth2/'

TWILIO_ACCOUNT_SID = 'AC9e2efef302ac1461eb1a5958fa8c3aec'
TWILIO_AUTH_TOKEN = 'c8e904faf3eb63094d6ebf0cb9af9329'
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+14155238886'
COUNTRY_CODE = '+91'
TWILIO_PHONE_NUMBER = '+17077239254'
# TWILIO_VERIFY_SERVICE_SID = os.getenv('VAc8eb1bb1ec1a13438932dac2f45125e7')

SOCIAL_AUTH_GITHUB_KEY = 'Ov23liwUScNTRAAKLQxv'
SOCIAL_AUTH_GITHUB_SECRET = '705de9d9ad8d5ea55ffcc295bb4999be215ebcc5'
SOCIAL_AUTH_GITHUB_REDIRECT_URI = 'http://127.0.0.1:8000/callback/'
#
# PAYPAL_CLIENT_ID = 'AQu8Zdm-ZjCvnu1KCdH5GLP9wB6nwLhDLxgaBiSf-7h7YK9AqEfM4Zc8bAN9Afg9U56_80wfYhSHAF5n'
# PAYPAL_SECRET_KEY = 'EAp4pBtXucZWbt0_NlFJ9WB9RbTyL23ULG6FIxKVDLhWxB20GOAXK2nduPYUEndBnmDokrP4ykK1cHaO'
# PAYPAL_MODE = 'live'

COOKIELAW_ACCEPT_ALL_BUTTON = True
COOKIELAW_MODAL = True
COOKIELAW_CONSENT_EXPIRE_AFTER_DAYS = 20
COOKIELAW_CONSENT_PREFIX = 'cookielaw_'
COOKIELAW_HIDE_AFTER = 'cookie_law_accepted'

# PAYPAL_RECEIVER_EMAIL = 'dilipkarmakar1978@gmail.com'
