# Generated by Django 5.0 on 2024-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('userno', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('Gender', models.CharField(max_length=6)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=10)),
                ('course', models.CharField(default=0, max_length=30)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Register_Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('UserName', models.CharField(max_length=40)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Password_id', models.CharField(max_length=30)),
                ('Country_Code', models.CharField(max_length=7)),
                ('Phone_number_id', models.CharField(max_length=12)),
            ],
        ),
    ]
