# Generated by Django 5.0 on 2024-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register_res',
            name='Password_id',
            field=models.CharField(max_length=400),
        ),
    ]
