from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.homefn, name='home'),
    path('home/', views.homefn),
    # path('registration/Login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/Login/', auth_views.LoginView.as_view(), name='login'),
    path('about', views.about),
    path('student', views.student),
    path('contactus', views.contactus),
    path('register', views.register1),
    path('logout/', views.logout1, name='Logout'),
    path('logout/logout', views.logout1, name='Logout'),
    path('otp/<int:id>/', views.otpVerify, name='otp'),
    path('otp//', views.otpVerify, name='otp'),
    path('otp/<int:id>/', views.otpVerify, name='otp'),
    # path('register/otp/<int:id>/', views.otpVerify, name='otp'),
    # path('register/otp/<int:id>/register', views.otpVerify, name='otp'),
    # path('otp/<int:id>/register', views.otpVerify, name='otp'),
    # path('register/', views.register1),
    # path('register/register', views.register1),
    path('Login', views.login12, name='Login'),
    # path('activate/(?P<uid64>[0>9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.activate1,
    #      name='activate'),
    path('activate/<uidb64>/<token>/', views.activate1, name='activate'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('register/Login', views.login12),
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path('student2', views.student2),
    path('Dashboard', views.dashboard),
    path('course', views.courses),
    path('editstd/<int:id>/', views.editUser),
    path('Users/', views.allinuser),
    path('Users/register', views.allinuser),
    path('editstd/<int:id>', views.editUser, name='editstd'),
    path('editstd/', views.editUser),
    path('delete_std/<int:id>', views.delete_std),
    path('viewstd/', views.viewstd),
    path('viewstd/<int:id>/', views.viewstd),
    path('viewstd/<int:id>/viewstd', views.viewstd),
    path('tar', views.train),
    path('alp', views.alp),
    path('pro', views.pro1),
    path('cat', views.cate),
    path('add/<int:id>', views.add_new),
    path('add', views.add_new),
    path('add/alp', views.add_new),
    path('Admm', views.axx),
    # path('back', views.back),
    path('ad_edit', views.ad_edit),
    path('ad_alluser', views.ad_alluser),
    path('message', views.message),
    path('rev', views.rev),
    path('pay', views.payment),
    path('pay/<int:id>', views.payment),
    path('pay/pay', views.payment),
    path('product_admin', views.products),
    path('inactive', views.inactive1, name='theme'),
    path('my_view/', views.my_view1, name='my_view'),
    # path('Contact45', views.Contatct2),
    path('Forget_pass/<int:id>/', views.Forget_pass),
    path('Otp_red/<int:id>/', views.Otp_red),
    path('Faculty_Page', views.Faculty_Page),
    # path('paypal/', include('paypal.standard.ipn.urls'))
    # path('payment_process/', views.payment_process, name='payment_process')
    # path('Otp_red', views.Otp_red)
    # path('otp/<function uuid4 at 0x000002A764690AE0>/back', views.back),

]
